name: Weather Forecast Generator
description: Generate a weather forecast table dynamically for README.md.
inputs:
  WEATHER_API_KEY:
    description: API key for the weather service
    required: true
  FORECAST_CITY:
    description: City for the weather forecast
    required: true
  FORECAST_DAYS:
    description: Number of forecast days
    required: false
    default: "3"
  GH_TOKEN:
    description: Token to solve authentication issues
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --build-arg
    - GH_TOKEN=${{ inputs.GH_TOKEN }}
  env:
    WEATHER_API_KEY: ${{ inputs.WEATHER_API_KEY }}
    FORECAST_CITY: ${{ inputs.FORECAST_CITY }}
    FORECAST_DAYS: ${{ inputs.FORECAST_DAYS }}
