name: Weather Forecast Generator
description: Generate a weather forecast table dynamically for README.md.
inputs:
  weather-api-key:
    description: API key for the weather service
    required: true
  city:
    description: City for the weather forecast
    required: true
  days:
    description: Number of forecast days
    required: false
    default: "3"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.weather_api_key }}
    - ${{ inputs.forecast_city }}
    - ${{ inputs.forecast_days }}
  env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    REPO_URL: "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/assets/img"
