name: "Update Weather"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"  # Runs once a day at 7 AM UTC
  
jobs:
  run-weather-app:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run Action
        uses: MaarceloLuiz/springboot-weather-forecast@v1.0.1
        with:
          weather_api_key: ${{ secrets.WEATHER_API_KEY }}
          forecast_city: ${{ vars.FORECAST_CITY }}
          forecast_days: ${{ vars.FORECAST_DAYS }}
          
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Update weather data" || echo "No changes to commit"
          git push origin main
